services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-jkt
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # cuma default bisa diganti
      MONGO_INITDB_ROOT_PASSWORD: password123 # sama bisa diganti juga
    ports:
      - "27017:27017" # port lokal dan container 27017
    volumes:
      - mongodb_data:/data/db # Menguhubungkan /data/db dari container mongodb ke volume mongodb _data

  api:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile # Path Dockerfile
    env_file:
      - ../.env # Path env (bikin env dlu)
    ports:
      - "8000:8000" # Port FastAPI

volumes:
  mongodb_data:
